### ISSUE TITLE
Go back button doesn't scale properly on some systems

### ISSUE THREAD

**Issue by lunakurame** [kurogetsusai/firefox-gnome-theme#17]
The "go back" button seems to look fine on my system and any other system I run on a virtual machine, but it seems to not scale properly for some people, eg. it was reported to be too big in issue #2 (Firefox 57), also it seems blurred (slightly too big?) on the screenshots from issue #7 (Firefox 58 or 59).

It would be nice if anyone could find a reason why does it behave like that, or any way for me to reproduce it, so I can fix it.

**Comment by smithfred** [comment]
The offending rule is:

```css
#back-button > .toolbarbutton-icon {
	width: 30px !important;
}
```

The standard rule from browser.css is:

```css
#back-button > .toolbarbutton-icon {
	width: calc(2 * var(--toolbarbutton-inner-padding) + 16px);
}
```

This results in a computed value of 26px (16px, plus 5+5px padding) instead of 30px.

I think you'll find that the "some systems" seeing this problem have "Compact" density selected in Firefox's "Customise" UI instead of "Normal" - removing the above rule fixes the oversized/blurry icon in that case ;)

On the other hand, with "Normal" density the back icon looks undersized without the 30px rule.

HTH
