### ISSUE TITLE
possible to have a curve tab?

### ISSUE THREAD

**Issue by thyeun** [kurogetsusai/firefox-gnome-theme#5]
As show as below picture

![selection_004](https://user-images.githubusercontent.com/1939446/33720103-e119b74a-db9d-11e7-8272-6a8c392800b3.png)

**Comment by ghost** [comment]
Adwaita doesn't have curved tabs.

**Comment by lunakurame** [comment]
Yeah, I'm not gonna add this, because Adwaita doesn't have curved tabs, and I don't even know how to make it look like that. You can add curved corners at the top of the active tab like this:

```css
.tab-background[selected=true] {
	border-top-left-radius: 10px;
	border-top-right-radius: 10px;
}
```

But I don't know how to make those curves at the bottom and it probably wouldn't work with this theme anyway (because of space between tabs and border-bottom of the active tab).
